services:
  - type: web
    name: training-tracker-backend
    env: node
    region: singapore
    buildCommand: npm install && npm run migrate
    startCommand: npm start
    healthCheckPath: /api/employees
    envVars:
      - key: NODE_ENV
        value: production
      - key: PORT
        value: 3001
